version: "3"

services:
  lb:
    image: ionutbotizan/hello-docker-net
    build: .
    ports:
      - "80:80"
    depends_on:
      - hello-docker-app-1
      - hello-docker-app-2

  hello-docker-app-1:
    image: ionutbotizan/hello-docker-app
    ports:
      - "8001:8080"
    environment:
      - INSTANCE_NO=1

  hello-docker-app-2:
    image: ionutbotizan/hello-docker-app
    ports:
      - "8002:8080"
    environment:
      - INSTANCE_NO=2

  hello-world:
    image: hello-world
